## Setup

In [4]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

from dataset import TranslationDataset, get_dataloader
from vocab import Vocab

import logging
# logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logging.basicConfig(format="%(levelname)s:%(name)s:  %(message)s")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/iliarudiak/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:
logging.getLogger("nmt").setLevel(logging.DEBUG)

In [ ]:
logging.getLogger("nmt").setLevel(logging.INFO)

## 01 Dataset and Dataloaders

### 01 Dataset

In [19]:
src_file_path = 'zh_en_data/train_1K.zh'
tgt_file_path = 'zh_en_data/train_1K.en'
vocab = Vocab.load('vocab.json')
dataset = TranslationDataset(src_file_path=src_file_path, 
                             tgt_file_path=tgt_file_path,
                             src_vocab=vocab.src,
                             tgt_vocab=vocab.tgt,
                             max_samples=2)

DEBUG:nmt.dataset:  ===line_idx=0===
DEBUG:nmt.dataset:  tgt_pieces=['<s>', '▁he', '▁was', '▁seen', '▁wear', 'ing', '▁a', '▁white', '▁', 'jacket', ',', '▁a', '▁dark', '-', 'coloured', '▁t', '-', 'shi', 'rt', '▁and', '▁p', 'ants', '.', '</s>']
DEBUG:nmt.dataset:  tgt_ids=[1, 49, 23, 891, 2750, 20, 12, 2258, 19, 7854, 7, 12, 3792, 13, 7992, 517, 13, 3622, 2331, 10, 427, 3221, 5, 2]
DEBUG:nmt.dataset:  ===line_idx=1===
DEBUG:nmt.dataset:  tgt_pieces=['<s>', '▁they', '▁were', '▁also', '▁briefed', '▁by', '▁the', '▁physical', '▁education', '▁and', '▁recreation', '▁management', '▁society', '▁of', '▁hong', '▁kong', '▁ba', 'pt', 'ist', '▁university', '▁on', '▁the', '▁relationship', '▁between', '▁doing', '▁exercise', 's', '▁and', '▁physical', '▁well', '-', 'being', '.', '</s>']
DEBUG:nmt.dataset:  tgt_ids=[1, 59, 42, 41, 4485, 22, 4, 1587, 214, 10, 4662, 391, 419, 6, 58, 57, 1163, 2662, 847, 662, 18, 4, 1016, 125, 1383, 745, 11, 10, 1587, 129, 13, 2940, 5, 2]


In [12]:
len(dataset)

2

In [16]:
sample_src, sample_tgt = dataset[0]
type(sample_src), sample_src.shape

(torch.Tensor, torch.Size([17]))

In [18]:
sample_src, sample_tgt

(tensor([    7,  8735,    33,  7695,  8367,   189,  3082,     4,  1072,  1517,
            35,  3082,    17,  1072,  1517, 13275,     5]),
 tensor([   1,   49,   23,  891, 2750,   20,   12, 2258,   19, 7854,    7,   12,
         3792,   13, 7992,  517,   13, 3622, 2331,   10,  427, 3221,    5,    2]))

### 02 Data Loaders

In [20]:
loader = get_dataloader(dataset=dataset,
                        batch_size=2,
                        shuffle=False)

In [25]:
batch = next(iter(loader))
src_padded, src_lengths, tgt_padded = batch

In [27]:
src_lengths

[19, 17]

In [26]:
type(batch), type(src_padded), type(src_lengths), type(tgt_padded)

(tuple, torch.Tensor, list, torch.Tensor)

In [30]:
tgt_padded.T

tensor([[   1,   59,   42,   41, 4485,   22,    4, 1587,  214,   10, 4662,  391,
          419,    6,   58,   57, 1163, 2662,  847,  662,   18,    4, 1016,  125,
         1383,  745,   11,   10, 1587,  129,   13, 2940,    5,    2],
        [   1,   49,   23,  891, 2750,   20,   12, 2258,   19, 7854,    7,   12,
         3792,   13, 7992,  517,   13, 3622, 2331,   10,  427, 3221,    5,    2,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])